---
- name: Update Sources
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  when: ansible_distribution == 'Debian'

- name: Update Sources
  template:
    src: sources.list-ub.j2
    dest: /etc/apt/sources.list
  when: ansible_distribution == 'Ubuntu'

- name: Update and upgrade apt packages
  become: yes
  become_user: root
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_res
  until: apt_res is success
  retries: 10
  delay: 3

- name: Install Packages
  become: yes
  become_user: root
  apt:
    pkg:
      - make
      - gcc
      - unzip
      - sqlite3
      - python
      - golang 
      - gparted
      - p7zip-full
      - zip
      - p7zip
      - openssl
      - sudo
      - vim
      - net-tools
      - file-roller 
      - evince 
      - qalculate 
      - clementine 
      - vlc 
      - gimp 
      - shotwell 
      - gparted 
      - gnome-disk-utility 
      - libreoffice-writer 
      - libreoffice-calc 
      - libreoffice-impress 
      - libavcodec-extra 
      - ffmpeg
      - pavucontrol
      - apt-transport-https 
      - libcurl3
      - rsync
    state: present
    install_recommends: yes

  register: apt_res
  until: apt_res is success
  retries: 10
  delay: 3

- name: Install Debian Specific Packages
  become: yes
  become_user: root
  apt:
    pkg:
      - firefox-esr
      - ttf-freefont
      - curl

  when: ansible_distribution == 'Debian'

- name: Install Ubuntu Specific Packages
  become: yes
  become_user: root
  apt:
    pkg:
      - firefox
      - libcurl4
      - curl
  when: ansible_distribution == 'Ubuntu'

- name: Upgrade Dist
  become: yes
  become_user: root
  apt:
    upgrade: dist
    update_cache: yes
    dpkg_options: 'force-confold,force-confdef'
  register: apt_res
  until: apt_res is success
  retries: 10
  delay: 3

- name: Remove mutt
  become: yes
  become_user: root
  apt: name=mutt state=absent
