---
- name: Install Packages
  apt: 
    pkg:
      - xfce4
      - xfce4-mount-plugin
      - xfce4-notifyd
      - xfce4-places-plugin
      - xfce4-goodies
      - xfce4-power-manager
      - xfce4-battery-plugin
      - lightdm
      - lightdm-settings
      - slick-greeter
#      - light-locker
#      - light-locker-settings
#      - bspwm
#      - sxhkd
      - xcb 
      - libxcb-util0-dev 
      - libxcb-ewmh-dev 
      - libxcb-randr0-dev 
      - libxcb-icccm4-dev 
      - libxcb-keysyms1-dev 
      - libxcb-xinerama0-dev 
      - libasound2-dev 
      - libxcb-xtest0-dev 
      - libxcb-shape0-dev
      - autoconf
      - bison
      - flex
      - libxcb-xrm0
      - rofi
      - htop
    state: present
  register: results
  until: results is success
  retries: 10
  delay: 3

#- name: Stop xfce4 panel
#  become: yes
#  become_user: "{{ username }}"
#  shell: xfce4-panel --quit
#  ignore_errors: yes

- name: Stop xfce4 panel
  become: yes
  become_user: "{{ username }}"
  shell: pkill xfconfd
  ignore_errors: yes
  when: ansible_distribution == 'Debian'

#- name: Disable Lockscreen
#  shell: "{{ item }}"
#  with_items:
#    - gsettings set org.gnome.desktop.session idle-delay 0
#    - gsettings set org.gnome.desktop.screensaver lock-enabled false
#    - gsettings set org.gnome.desktop.lockdown disable-lock-screen true
#  when: ansible_distribution == 'Ubuntu'

- name: Create xfce panel launcher directories
  become: yes
  become_user: "{{ username }}"
  file:
    path: /home/{{ username }}/.config/xfce4/panel/launcher-{{item}}/
    state: directory
    recurse: yes
  with_items:
    - 9
    - 10
    - 11
    - 12
    - 16
    - 17
    - 18
    - 19
    - 20
    - 32

- name: Create xfce-perchannel-xml directory
  become: yes
  become_user: "{{ username }}"
  file:
    path: /home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/
    state: directory
    recurse: yes

- name: Create xfce-perchannel-xml directory
  become: yes
  become_user: "{{ username }}"
  file:
    path: /home/{{ username }}/.config/{{ item }}/
    state: directory
    recurse: yes
  with_items:
    - bspwm
    - sxhkd

- name: Configure XFCE4 Power Managment
  become: yes
  become_user: "{{ username }}"
  template:
    src: xfce4-power-manager.j2
    dest: /home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml

- name: Configure XFCE4 Panels
  become: yes
  become_user: "{{ username }}"
  template:
    src: "{{ item.src }}"
    dest: '/home/{{ username }}/.config/xfce4/panel/launcher-{{ item.dest }}'
  with_items:
    - { src: 'exo-terminal-emulator.desktop', dest: '9/exo-terminal-emulator.desktop' }
    - { src: 'exo-file-manager.desktop', dest: '10/exo-file-manager.desktop' }
    - { src: 'xfce4-appfinder.desktop', dest: '12/xfce4-appfinder.desktop' }
    - { src: 'cherrytree.desktop', dest: '16/cherrytree.desktop' }
    - { src: 'google-chrome.desktop', dest: '17/google-chrome.desktop' }
    - { src: 'sublime_text.desktop', dest: '18/sublime_text.desktop' }
    - { src: 'keepass2.desktop', dest: '19/keepass2.desktop' }
    - { src: 'vmware.desktop', dest: '20/vmware.desktop' }
    - { src: 'evolution.desktop.j2', dest: '32/evolution.desktop' }

- name: Configure Firefox Panel (Debian)
  become: yes
  become_user: "{{ username }}"
  template:
    src: "{{ item.src }}"
    dest: '/home/{{ username }}/.config/xfce4/panel/launcher-{{ item.dest }}'
  with_items:
    - { src: 'firefox-esr.desktop', dest: '11/firefox.desktop' }
  when: ansible_distribution == 'Debian'

- name: Configure Firefox Panel (Ubuntu)
  become: yes
  become_user: "{{ username }}"
  template:
    src: "{{ item.src }}"
    dest: '/home/{{ username }}/.config/xfce4/panel/launcher-{{ item.dest }}'
  with_items:
    - { src: 'firefox.desktop', dest: '11/firefox.desktop' }
  when: ansible_distribution == 'Ubuntu'

- name: Configure XFCE4 Panels
  become: yes
  become_user: "{{ username }}"
  template:
    src: "{{ item.src }}"
    dest: '/home/{{ username }}/.config/xfce4/panel/{{ item.dest }}'
  with_items:
    - { src: 'cpugraph-25.rc.j2', dest: 'cpugraph-25.rc' }
    - { src: 'fsguard-34.rc.j2', dest: 'fsguard-34.rc' }
    - { src: 'netload-28.rc.j2', dest: 'netload-28.rc' }
    - { src: 'systemload-27.rc.j2', dest: 'systemload-27.rc' }

#- name: Configure XFCE
#  become: yes
#  become_user: "{{ username }}"
#  command: "{{ item }}"
#  with_items:
#  - xfconf-query -n -a -c xfce4-panel -p /panels -t int -s 0
#  - xfconf-query --create --channel xfce4-panel --property /panels/panel-0/plugin-ids -t int -s 1   -t int -s 2   -t int -s 3   -t int -s 4   -t int -s 5  ${_TMP}        -t int -s 7   -t int -s 8  -t int -s 9 -t int -s 10  -t int -s 11  -t int -s 13  -t int -s 15  -t int -s 16  -t int -s 17  -t int -s 19  -t int -s 20
#  - xfconf-query -n -c xfce4-panel -p /panels/panel-0/length -t int -s 100
#  - xfconf-query -n -c xfce4-panel -p /panels/panel-0/size -t int -s 30
#  - xfconf-query -n -c xfce4-panel -p /panels/panel-0/position -t string -s "p=6;x=0;y=0"
#  - xfconf-query -n -c xfce4-panel -p /panels/panel-0/position-locked -t bool -s true
#  # application menu
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-1 -t string -s applicationsmenu
#  # terminal   ID: exo-terminal-emulator
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-2 -t string -s launcher
#  # places
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-3 -t string -s places
#  # wireshark  ID: kali-wireshark
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-4 -t string -s launcher
#  # firefox    ID: firefox-esr
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-5 -t string -s launcher
#  # burpsuite  ID: kali-burpsuite
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-6 -t string -s launcher
#  # msf        ID: kali-msfconsole
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-7 -t string -s launcher
#  # gedit      ID: org.gnome.gedit.desktop
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-8 -t string -s launcher
#  # search     ID: xfce4-appfinder
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-9 -t string -s launcher
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-10 -t string -s tasklist
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-11 -t string -s separator
#  # audio
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-13 -t string -s mixer
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-15 -t string -s systray
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-16 -t string -s actions
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-17 -t string -s clock
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-19 -t string -s pager
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-20 -t string -s showdesktop
#  #--- application menu
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-1/show-tooltips -t bool -s true
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-1/show-button-title -t bool -s false
#  #--- terminal
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-2/items -t string -s "exo-terminal-emulator.desktop" -a
#  #--- places
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-3/mount-open-volumes -t bool -s true
#  #--- wireshark
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-4/items -t string -s "kali-wireshark.desktop" -a
#  #--- firefox
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-5/items -t string -s "firefox-esr.desktop" -a
#  #--- burp
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-6/items -t string -s "kali-burpsuite.desktop" -a
#  #--- metasploit
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-7/items -t string -s "kali-msfconsole.desktop" -a
#  #--- gedit
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-8/items -t string -s "textedit.desktop" -a
#  #--- search
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-9/items -t string -s "xfce4-appfinder.desktop" -a
#  #--- tasklist (& separator - required for padding)
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-10/show-labels -t bool -s true
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-10/show-handle -t bool -s false
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-11/style -t int -s 0
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-11/expand -t bool -s true
#  #--- systray
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-15/show-frame -t bool -s false
#  #--- actions
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-16/appearance -t int -s 1
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-16/items -t string -s "+logout-dialog"  -t string -s "-switch-user"  -t string -s "-separator" -t string -s "-logout"  -t string -s "+lock-screen"  -t string -s "+hibernate"  -t string -s "+suspend"  -t string -s "+restart"  -t string -s "+shutdown"  -a
#  #--- clock
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-17/show-frame -t bool -s false
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-17/mode -t int -s 2
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-17/digital-format -t string -s "%R, %Y-%m-%d"
#  #--- pager / workspace
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-19/miniature-view -t bool -s true
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-19/rows -t int -s 1
#  - xfconf-query -n -c xfwm4 -p /general/workspace_count -t int -s 3
#  #--- Theme options
#  - xfconf-query -n -c xsettings -p /Net/ThemeName -s "Kali-X"
#  - xfconf-query -n -c xsettings -p /Net/IconThemeName -s "Vibrancy-Kali"
#  - xfconf-query -n -c xsettings -p /Gtk/MenuImages -t bool -s true
#  - xfconf-query -n -c xfce4-panel -p /plugins/plugin-1/button-icon -t string -s "kali-menu"
#  #--- Window management
#  - xfconf-query -n -c xfwm4 -p /general/snap_to_border -t bool -s true
#  - xfconf-query -n -c xfwm4 -p /general/snap_to_windows -t bool -s true
#  - xfconf-query -n -c xfwm4 -p /general/wrap_windows -t bool -s false
#  - xfconf-query -n -c xfwm4 -p /general/wrap_workspaces -t bool -s false
#  - xfconf-query -n -c xfwm4 -p /general/click_to_focus -t bool -s false
#  - xfconf-query -n -c xfwm4 -p /general/click_to_focus -t bool -s true
#  #--- Hide icons
#  - xfconf-query -n -c xfce4-desktop -p /desktop-icons/file-icons/show-filesystem -t bool -s false
#  - xfconf-query -n -c xfce4-desktop -p /desktop-icons/file-icons/show-home -t bool -s false
#  - xfconf-query -n -c xfce4-desktop -p /desktop-icons/file-icons/show-trash -t bool -s false
#  - xfconf-query -n -c xfce4-desktop -p /desktop-icons/file-icons/show-removable -t bool -s false
#  #--- Start and exit values
#  - xfconf-query -n -c xfce4-session -p /splash/Engine -t string -s ""
#  - xfconf-query -n -c xfce4-session -p /shutdown/LockScreen -t bool -s true
#  - xfconf-query -n -c xfce4-session -p /general/SaveOnExit -t bool -s false
#  #--- App Finder
#  - xfconf-query -n -c xfce4-appfinder -p /last/pane-position -t int -s 248
#  - xfconf-query -n -c xfce4-appfinder -p /last/window-height -t int -s 742
#  - xfconf-query -n -c xfce4-appfinder -p /last/window-width -t int -s 648
#  #--- Enable compositing
#  - xfconf-query -n -c xfwm4 -p /general/use_compositing -t bool -s true
#  - xfconf-query -n -c xfwm4 -p /general/frame_opacity -t int -s 85

#- name: Remove "Mail Reader" from menu
#  template:
#    src: exo-mail-reader.j2
#    dest: /usr/share/applications/exo-mail-reader.desktop

#- name: XFCE default applications
#  become: yes
#  become_user: "{{ username }}"
#  template:
#    src: mimeapps.j2
#    dest: /home/{{ username }}/.local/share/applications/mimeapps.list

- name: XFCE keyboard shortcuts
  become: yes
  become_user: "{{ username }}"
  template:
    src: xfce4-keyboard-shortcuts.xml.j2
    dest: /home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml

- name: XFCE helpers
  become: yes
  become_user: "{{ username }}"
  template:
    src: helpers.j2
    dest: /home/{{ username }}/.config/xfce4/helpers.rc

#- name: Setting Default X
#  become: yes
#  become_user: "{{ username }}"
#  command: "update-alternatives --set x-session-manager /usr/bin/xfce4-session"
#  #update-alternatives --config x-session-manager

- name: Copy over XFCE desktop xml # Template not working 
  become: yes
  become_user: "{{ username }}"
  template:
    src: xfce4-desktop.xml.j2
    dest: /home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml

- name: Copy over XFCE panel xml # Template not working 
  become: yes
  become_user: "{{ username }}"
  template:
    src: xfce4-panel.xml.j2
    dest: /home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml

- name: Copy over XFCE Settings # Template not working 
  become: yes
  become_user: "{{ username }}"
  template:
    src: XFCE-xsettings.xml.j2
    dest: /home/{{ username }}/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

####################################################################################################
### Backup for issues copying over template panels
- name: Copy over XFCE panel xml # Template not working 
  become: yes
  become_user: "{{ username }}"
  template:
    src: xfce4-panel.xml.j2
    dest: /home/{{ username }}/.config/xfce4/xfce4-panel.xml

- name: Copy over XFCE panel replace script # Template not working 
  become: yes
  become_user: "{{ username }}"
  template:
    src: XFCE-panel.sh.j2
    dest: /home/{{ username }}/.config/xfce4/XFCE-panel.sh
    mode: 0755

- name: Backup copy execute  
  become: yes
  become_user: "{{ username }}"
  shell: /home/{{ username }}/.config/xfce4/XFCE-panel.sh
####################################################################################################

- name: Clone bspwm repo
  git: 
    repo: https://github.com/baskerville/bspwm.git
    dest: /tmp/bspwm-git/
  register: results
  until: results is success
  retries: 10
  delay: 3

- name: Clone sxhkd repo
  git: 
    repo: https://github.com/baskerville/sxhkd.git
    dest: /tmp/sxhkd-git/
  register: results
  until: results is success
  retries: 10
  delay: 3

- name: Build bspwm
  shell: chdir=/tmp/bspwm-git/ {{ item }}
  with_items:
    - make 
    - make install

- name: Build sxhkd
  shell: chdir=/tmp/sxhkd-git/ {{ item }}
  with_items:
    - make
    - make install

- name: Copy over bspwm config
  become: yes
  become_user: "{{ username }}"
  template:
    src: bspwmr.j2
    dest: /home/{{ username }}/.config/bspwm/bspwmrc
    mode: 0755

- name: Copy over bspwm monitor script
  become: yes
  become_user: "{{ username }}"
  template:
    src: multi-monitor.sh.j2
    dest: /home/{{ username }}/.config/bspwm/multi-monitor.sh
    mode: 0755

- name: Copy over sxhkd config
  become: yes
  become_user: "{{ username }}"
  template:
    src: sxhkdrc.j2
    dest: /home/{{ username }}/.config/sxhkd/sxhkdrc

- name: bspwm autostart
  become: yes
  become_user: "{{ username }}"
  template:
    src: bspwm.desktop.j2
    dest: /home/{{ username }}/.config/autostart/bspwm.desktop

- name: sxhkd autostart
  become: yes
  become_user: "{{ username }}"
  template:
    src: sxhkd.desktop.j2
    dest: /home/{{ username }}/.config/autostart/sxhkd.desktop

- name: Move xfdesktop and xfwm4 to "disable"
  command: mv {{ item }}
  with_items:
#    - /usr/bin/xfdesktop /usr/bin/xfdesktop.bk
    - /usr/bin/xfwm4 /usr/bin/xfwm4.bk
  ignore_errors: yes

# Greeter config
- name: lightdm config
  template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf

- name: Slick Greeter config
  template:
    src: slick-greeter.conf.j2
    dest: /etc/lightdm/slick-greeter.conf