---
- name: Add non-free Source
  template:
    src: non-free.j2
    dest: /etc/apt/sources.list.d/non-free.list

- name: Install Packages
  become: yes
  become_user: root
  apt: name=firmware-iwlwifi state=latest update_cache=true
  register: apt_res
  until: apt_res is success
  retries: 10
  delay: 3

---
- name: Install Packages
  apt: 
    pkg:
      - firmware-linux-nonfree
    state: present
  register: results
  until: results is success
  retries: 10
  delay: 3

